trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
- job: "Run code coverage"
  pool:
    vmImage: 'windows-latest'
    demands:
    - msbuild
  steps:
    - template: build/template-install-dotnet-core.yaml
    - template: build/template-install-keyvault-secrets.yaml
    - task: DotNetCoreCLI@2
      inputs:
        projects: 'Microsoft.Identity.Web.sln'
        command: 'restore'
    - task: VSBuild@1
      inputs:
        solution: Microsoft.Identity.Web.sln
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: test
        projects: 'tests/**/Microsoft.Identity.Web.Test*.csproj'
        arguments: '--collect "Code coverage"'
