trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
- job: "code_coverage"
  pool:
    vmImage: 'windows-latest'
    demands:
    - msbuild
  steps:
    - template: build/template-install-dotnet-core.yaml
    - template: build/template-install-keyvault-secrets.yaml
    - task: DotNetCoreCLI@2
      inputs:
        projects: 'Microsoft.Identity.Web.sln'
        command: 'restore'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: test
        projects: | 
          tests/**/Microsoft.Identity.Web.Test*.csproj
          !tests/**/Microsoft.Identity.Web.Test.LabInfrastructure.csproj
          !tests/**/xunit.assert.dll
        arguments: '-f net7.0 --collect "Code coverage"'
