trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
- job: "PR_build"
  pool:
    name: MwWilson1EsHostedPool
    demands:
    - msbuild
  steps:
    - template: build/template-install-dependencies.yaml
    - template: build/template-run-unit-tests.yaml
