name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: IdWeb GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup .NET 3.1.301
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.301        
    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 7.0.x
  
    # Install workload
    - name: Setup wasm-tools
      run: dotnet workload install wasm-tools
        
    - name: Build with .NET 3.1.301
      run: dotnet test -f 3.1.301 -p:FROM_GITHUB_ACTION=true --configuration Release Microsoft.Identity.Web.sln
      
    - name: Build with .NET 7.0.x
      run: dotnet test -f 7.0 -p:FROM_GITHUB_ACTION=true --configuration Release Microsoft.Identity.Web.sln
