name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: IdWeb GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup .NET 3.1.301
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.301
    - name: Build with .NET 3.1.301
      run: dotnet test -f 3.1.301 -p:FROM_GITHUB_ACTION=true --configuration Release Microsoft.Identity.Web.sln

    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup .NET 6.0.301
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.301
    # Install workload
    - name: Setup wasm-tools
      run: dotnet workload install wasm-tools
    - name: Build with .NET 6.0.301
      run: dotnet test -f 6.0.301 -p:FROM_GITHUB_ACTION=true --configuration Release Microsoft.Identity.Web.sln
