name: .NET Core

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - "master"
    paths:
      - ".github/workflows/dotnetcore.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: IdWeb GitHub Action Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup .NET 3.1.301
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.301

    - name: Setup .NET 6.0.301
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.301

    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 7.0.x
  
    # Install workload
    - name: Setup wasm-tools
      run: dotnet workload install wasm-tools

    - name: Build with .NET 6.0.x
      run: dotnet test Microsoft.Identity.Web.sln -f net6.0 -p:FROM_GITHUB_ACTION=true --configuration Release --filter "(FullyQualifiedName!~Microsoft.Identity.Web.Test.Integration)&(FullyQualifiedName!~WebAppUiTests)&(FullyQualifiedName!~IntegrationTests)"

    - name: Build with .NET 7.0.x
      run: dotnet test Microsoft.Identity.Web.sln -f net7.0 -p:FROM_GITHUB_ACTION=true --configuration Release --filter "(FullyQualifiedName!~Microsoft.Identity.Web.Test.Integration)&(FullyQualifiedName!~WebAppUiTests)&(FullyQualifiedName=IntegrationTests)"
